In [1]:
import numpy as np

In [2]:
def insertion_sort(A):
    """Sorts a list A using the insertion sort algorithm.
    Run-time: Θ(n^2)
    Space: Θ(1)
    """
    for j in range(2, len(A)):
        key = A[j]
        
        # insert A[j] into the sorted sequence A[1 .. j - 1]
        i = j - 1
        while i > 0 and A[i] > key:
            A[i + 1] = A[i]
            i = i - 1
        A[i + 1] = key
    
    return A

In [3]:
A = [1, 2, 4, 5, 6, 7, 3, 9, 8, 10]

print(insertion_sort(A))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [4]:
def square_matrix_multiply(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    """Multiplies two square matrices A and B.
    Run-time: Θ(n^3)
    Space: Θ(n^2)
    """
    n = A.shape[0]
    C = np.ones((n, n))
    for i in range(n):
        for j in range(n):
            C[i, j] = 0
            for k in range(n):
                C[i, j] += A[i, k] * B[k, j]

    return C

In [5]:
def strassen_multiply(X: np.ndarray, Y: np.ndarray) -> np.ndarray:
    """Multiplies two equally sized square matrices of power 2 via Strassen.
    Run-time: Θ(n^log2(7)) -> Θ(n^2.81)
    Space: Θ(n^2)
    """

    n = X.shape[0]

    if n == 1:
        return X * Y

    A = X[:n//2, :n//2] 
    B = X[:n//2, n//2:]
    C = X[n//2:, :n//2]
    D = X[n//2:, n//2:]
    E = Y[:n//2, :n//2]
    F = Y[:n//2, n//2:]
    G = Y[n//2:, :n//2]
    H = Y[n//2:, n//2:]

    P1 = strassen_multiply(A + D, E + H)
    P2 = strassen_multiply(C + D, E)
    P3 = strassen_multiply(A, F + H)
    P4 = strassen_multiply(D, G - E)
    P5 = strassen_multiply(A + B, H)
    P6 = strassen_multiply(C - A, E + F)
    P7 = strassen_multiply(B - D, G + H)

    top_left = P1 + P4 - P5 + P7
    top_right = P3 + P5
    bottom_left = P2 + P4
    bottom_right = P1 - P2 + P3 + P6

    top = np.hstack((top_left, top_right))
    bottom = np.hstack((bottom_left, bottom_right))

    result = np.vstack((top, bottom))
    return result

In [6]:
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]], dtype=int)

B = np.array([[16, 15, 14, 13],
              [12, 11, 10, 9],
              [8, 7, 6, 5],
              [4, 3, 2, 1]], dtype=int)

print(A @ B)
#print(square_matrix_multiply(A, B))
print(strassen_multiply(A, B))

[[ 80  70  60  50]
 [240 214 188 162]
 [400 358 316 274]
 [560 502 444 386]]
[[ 80 110  80  92]
 [240 254 272 252]
 [400 622 336 476]
 [560 766 528 636]]
